### ISSUE TITLE
Paired Samples

### ISSUE THREAD

**Issue by jgeller112** [cvoeten/permutes#1]
I am happy that you created something in R that is comparable to MNE-Python and Fieldtrip stat functions.  

One concern I have is that the function does not take into account paired samples.   Could one take the difference between two conditions and perform a one-sample test across time points like in MNE-Python and Fieldtrip? 

-Jason

**Comment by cvoeten** [comment]
I'm not familiar with MNE or Fieldtrip, but your description is clear enough that I understand the issue.

If you only have one effect to test and have only two measurements, then you can indeed do as you suggest. Create a data frame with two columns (one for each measurement), subtract the two, and use the difference score as your dependent variable.

Another option, which also works if you have more than 2 measurements, is to formulate your model as an ANOVA and use the `Error()` function to specify the hierarchical structure. E.g. if my manipulation is `X` and I tested that multiple times in different participants, my model would become `dep ~ X + Error(participant/X)`. You should take a look at function `aovp` from package `lmPerm` for more details and caveats. This is the function that `permutes` uses for doing the underlying computation. If this is the solution you go for, let me know if it works -- I never tried this so I may need to add some extra code to `permutes` to parse the output of such a model.

If you need more than one random factor (e.g. both Subject and Item), you are essentially asking for a mixed-effects model. I'm afraid that that's not feasible. `permutes` uses `lmPerm` as the fitting backend because it uses a computational trick which makes the calculation of permutation p-values nearly instantaneous. This does not extend to mixed-effects models, so getting 5,000 permuted p-values would involve actually fitting 5,000 mixed-effects models, which is not feasible to do for every effect on every time point.

In sum, yes, if differencing is possible for your problem that's the way to go, otherwise reformulate your model as an ANOVA and use the `Error()` formulation. Your final option is to just ignore the paired structure in your data. I personally only use permutation tests as an exploratory tool to select an appropriate window for analysis, not as a formal test for actual inference. If this is also the case for you, you can make the case that incorporating random effects is premature at this step. But this is all up to you!

**Comment by cvoeten** [comment]
A bit late, but v2.0 which is now on Github and should make its way to CRAN soon implements permutation mixed-effects regression. See functions `perm.lmer` (which simply gives permutation p-values) and `clusterperm.lmer` (which repeats the same over many levels of a factor, e.g. timepoints, and computes cluster-mass statistics per Maris & Oostenveld 2007).
