### ISSUE TITLE
perm.glmer fits glm instead of glmer

### ISSUE THREAD

**Issue by AmeBol** [cvoeten/permutes#2]
Dear Cesko Voeten,

I was ecstatic seeing your package when I was searching for a way of running a permutation test for my glmer.nb-Models. It seems to be a great tool. I was aiming to do permutation tests because my residuals were heteroscedastic and I was supposed to check whether permuted p-values were different to the original ones. 
I used ```perm.glmer()``` for models with random effect intercept on count data with ```family = neg.bin(theta=theta)``` for 4 different outcomes but same model structure. I took theta from the original glmer-Model. I checked the p-values with ```summary()``` and ```anova()```.
Unfortunatly, the structure of the results leaves me puzzled. For 3 outcomes, the summary call states:
```
perm_model_1 <- perm.glmer(outcome1 ~ events*group*time + (1|code) 
                          ,data=data_long
                          ,family = neg.bin(theta=3.0518)
                          ,nperm = 10000
                          ,type= "anova")
summary(perm_model_1)
Call:
stats::glm(formula = outcome1 ~ 1 + time + group + time:group + events + time:event + group:events + 
    events:group:time, family = family, data = data)
...
```
It seems like the random effect was dropped, even though I included it in the formula.
 For the fourth Outcome, the summary call states:
```
summary(perm_model_4)
Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) ['glmerMod']
 Family: Negative Binomial(1.4504)  ( log )
Formula: outcome4 ~ events * group * time + (1 | code)
   Data: data_long
Control: glmerControl(optimizer = "bobyqa")
...
```

**Q1: Why did buildmer build glm-models and how can I specify that is builds glmer-Models?**
_Edit: After inspecting buildmer, I saw that it tries to find the all-siginifcant-term structure and hence builds glm for my models, since it finds my RE not to be significant. Because I have repeated measures and want to compare the perm.glmer to the glmer.nb, I would like to include the term anyways. Is there any chance how I can do that with buildmer, so that perm.glmer fits a glmer for my full model?_

___________________________________________________________________________________________________________________________________

The p-values I am interested in are the ones for the whole fixed effect, hence the ones from ```anova()```.
The structure of the anova differs with the model structure:

- for glmer it gives the ```Analysis-of-Deviance table (Type III sums of squares) with permutation p-values``` with Chisq, Df and  Pr(>Chisq). 
- for glm it gives the ```ANOVA table (Type III sums of squares) with permutation p-values``` with  Df, Chisq, Pr(>Chisq) and Pr(>F). 

**Q2: Why do those anova structures have to differ and what is the permutation p-value in both cases? It confuses me, that I get two different p-values for the glm-models (for F and Chisq)**

Looking foreward to your reply :)

**Comment by cvoeten** [comment]
Q1: evidently, your maximal model was not able to converge with the random intercept included. In this case, it will be dropped. This is also why the structure of the anova differs: the first three were from glm models, the last one was from a glmer model that did converge with your random intercept.

 

Q2: this is a bug in permutes, thank you for reporting it. The current code in permutes assumes that all generalized linear mixed models have a known scale parameter, which is actually only the case for binomial and poisson models. I’ll see how I can fix this bug (it turns out not to be too trivial), but to briefly answer your question regardless:

*	The column named “Chisq” is actually an F-value
*	The column named Pr(>F) is a Wald p-value
*	The column named Pr(>Chisq) is the permutation p-value

 

If it would be possible for you to share your data (or simulated data with the same characteristics), that would help me debug this more easily.

**Comment by AmeBol** [comment]
Concerning Q1: Is there any chance of keeping the n.s. random effect? I tried by including ```buildmerControl(include = include``` in perm.glmer, but that gave the error ```Weights have been provided, but are not of the same length as the data```. 

Concerning Q2: I will send you a dataset with the same characteristics to your email address at Leiden University.

**Comment by cvoeten** [comment]
Thanks, got it. I'll reply here instead of via e-mail.

For me, both o1 and o2 fit glmer models just fine. However, if I change o2's dependent variable to o1, it indeed fails to converge with the random intercept included. There is no way to force buildmer to retain the random intercept in that case, which is by design -- a nonconverged model should not be trusted. However, you may have luck changing the optimizer; my failing example can be gotten to converge if switching the default optimizer to bobyqa for both stages. I.e.:

```
perm.glmer(o1 ~ p1*p2*p3 + (1|code)
                      ,data=data_permutes
                      ,family = neg.bin(theta=3)
                      ,nperm = 10000
                      ,type= "anova"
                      ,buildmerControl=list(direction='order',control=lme4::glmerControl(optimizer=rep('bobyqa',2))))
```

Mind to specify the `direction='order'`; this is a default in `perm.glmer`, but if you change the default control argument, you need to include this explicitly. Otherwise, buildmer will also do backward stepwise elimination in an attempt to remove terms that are not significant according to the likelihood-ratio test, which is undesirable in the present context of permutation testing.

Next, the issue with the double p-values. That is clearly and obviously a permutes bug. I've done some rearchitecturing in permutes and pushed an update to GitHub. The easiest way to test it is to download the sources, unpack the `R/` directory, and `source()` all the files in there. Then try running your code again. For o2, I then get:

```
> perm.glmer(o2 ~ p1*p2*p3 + (1|code)
                      ,data=data_permutes
                      ,family = neg.bin(theta=3)
                      ,nperm = 10000
                      ,type= "anova"
                      ,buildmerControl=list(direction='order',control=lme4::glmerControl(optimizer=rep('bobyqa',2))))
One of the 8 permutation tests finished in 39.31248 secs 
One of the 8 permutation tests finished in 37.70053 secs 
One of the 8 permutation tests finished in 37.27421 secs 
One of the 8 permutation tests finished in 35.7718 secs 
One of the 8 permutation tests finished in 36.25956 secs 
One of the 8 permutation tests finished in 35.81144 secs 
One of the 8 permutation tests finished in 36.67647 secs 
One of the 8 permutation tests finished in 36.46015 secs 
    Factor df          LRT            F          p
1        1  1 11077.383153 2.519862e+03 0.00000000
2       p1  1    32.469480 1.901662e+01 0.02199780
3       p2  1     6.121006 8.790734e-05 0.81821818
4    p1:p2  1    47.870120 1.041838e+00 0.00009999
5       p3  1     1.850143 2.445515e+01 0.00489951
6    p1:p3  1     7.603129 1.881428e+00 0.00009999
7    p2:p3  1     4.719954 1.259760e+00 0.65133487
8 p1:p2:p3  1     2.812559 1.976223e+00 0.57734227

```

Does this address the issues you've run into?

**Comment by AmeBol** [comment]
Thank you so much for the reply and the effort you put in it! 

I did actually use the optimizer in ```lme4::glmer.nb()```, but did not know that I can include the same optimizer in ```buildmerControl```. I would have never come up with that! 

I downloaded the files, and sourced them in R, as you suggested. Unfortunately, I got an error while running it and it could not calculate the permutation tests. The error is as follows:
```
Error in `$<-.data.frame`(`*tmp*`, "cluster", value = NA) : 
  replacement has 1 row, data has 0 
8.
stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
    "replacement has %d rows, data has %d"), N, nrows), domain = NA) 
7.
`$<-.data.frame`(`*tmp*`, "cluster", value = NA) at C:\Users\permutes-master\R\buildmer.R#108
6.
`$<-`(`*tmp*`, "cluster", value = NA) at C:\Users\permutes-master\R\buildmer.R#108
5.
(function (formula, data = NULL, family = gaussian(), weights = NULL, 
    offset = NULL, series.var = ~0, buildmerControl = list(direction = "order", 
        crit = "LRT", quiet = TRUE, ddf = "lme4"), nperm = 1000, 
    type = "regression", parallel = FALSE, progress = "none")  ... 
4.
eval(mc, e) 
3.
eval(mc, e) at C:\Users\permutes-master\R\discoverability.R#91
2.
perm.lmer(...) at C:\Users\permutes-master\R\discoverability.R#152
1.
perm.glmer(o2 ~ p1*p2*p3 + (1|code), 
    data = data_permutes, family = neg.bin(theta = 3), 
    buildmerControl = list(direction = "order", control = lme4::glmerControl(optimizer = rep("bobyqa", 
        2))), nperm = 10000, type = "anova") 
```

**Comment by cvoeten** [comment]
Whoops, that was a small bug that I introduced accidentally. Try it now?

**Comment by AmeBol** [comment]
No worries! Tried it and it gives the same result structure as you gave above. So now it seems to work for my purpose, which is wonderful. Thank you so much!

```
perm.glmer(o3 ~ p1*p2*p3 + (1|code)
                      ,data=data_permutes
                      ,family = neg.bin(theta=3)
                      ,nperm = 10000
                      ,type= "anova"
                      ,buildmerControl=list(direction='order',control=lme4::glmerControl(optimizer=rep('bobyqa',2))))

                       Factor df         LRT            F          p
1          1  1 7608.680687 2.509802e+03 0.00000000
2         p1  2    5.373286 1.014286e+01 0.84561544
3         p2  1   30.716958 2.909507e-06 0.02759724
4      p1:p2  1   45.687605 1.066661e+00 0.00009999
5         p3  2    2.406786 1.530934e+01 0.05989401
6      p1:p3  2    3.892389 1.056546e+00 0.78242176
7      p2:p3  1   11.264768 1.285935e+00 0.00000000
8  p1:p2:p3   2    2.433288 1.213122e+00 0.71612839


```

Just a general thought: was it intended that the result of perm-glmer now is only the dataframe with n obs. (each fixed effect) of 5 variables (Factor, df, LRT, F, p)? Before, the function result was a lot more extensive with an complex object (containing e.g. beta-coefficients). For me, the functions result as you uploaded it in github exacly gives what I need. Just in case you want to push the update to CRAN, it might be of concern.

**Comment by AmeBol** [comment]
Sorry for having to come back once more, but I have been struggling to compare the permutation results. The table I obtained: 

- Is the table displaying the results of LRTs (e.g. row 8 is comparison of the full model with the model without p1*p2*p3) where predictors are successively are being dropped for each LRT (and the name of the dropped predictor is given in each row)? 

- Or is the result comparable to an anova with type 3 sum scores?

I thought it would be the successive dropping of predictor terms, but the existence of the intercept LRT throws me off.

Please excuse the inconvenience and my inexperience.

**Comment by cvoeten** [comment]
The latter: the LRTs are marginal, not sequential. It's actually a good
question, because I suppose there could be folks who might want Type I/II
ANOVA interpretations (if you're out there, please explain it to me - I've
never understood why one might desire to run a non-marginal ANOVA, except
in the special case of using Type I ANOVA to do stepwise elimination!). But
this is currently not implemented, so the only difference between
permutation ANOVA and regression in permutes is that ANOVA tests multiple
coefficients simultaneously.
