### ISSUE TITLE
No p-values

### ISSUE THREAD

**Issue by apike02** [cvoeten/permutes#6]
Hi, great package! I was just a bit unsure as to why my models aren't producing any p values. I have lmerTest loaded, in case that's the issue, but running even the example models using the MMN dataset isn't producing any p-values for me, even in a new R session. 

Here's sessionInfo() and a screenshot, in case these help. I have the latest version of buildmer. 
![Screenshot 2022-10-26 at 17 28 22](https://user-images.githubusercontent.com/26331350/198082162-e7be431a-e4d8-4c76-9e65-4edb12ab637c.png)

![Screenshot 2022-10-26 at 17 30 18](https://user-images.githubusercontent.com/26331350/198082564-05ec4e11-ee14-4040-b8b1-8d7dcae7eb3d.png)

**Comment by apike02** [comment]
Just noticed I'm also getting these warning messages, which seem relevant: 
![Screenshot 2022-10-26 at 17 56 07](https://user-images.githubusercontent.com/26331350/198088198-0e8e9025-4f91-402f-80d0-0d680d4cbac0.png)

**Comment by apike02** [comment]
Ok - updating everything (both buildmer and permutes, and the suggested dependencies) using devtools::install_github to the latest versions on here works. Still get the warning about number of items - this seems to be linked to the use of double square brackets [[ rather than [ around the call p$call$args[x] (a new edit I think).

**Comment by cvoeten** [comment]
Thanks for reporting. I'm not sure what happened with the first issue, but since it now seems to be resolve, let's leave it at that. The second issue is indeed a bug - or rather, something that I thought was necessary but turns out it wasn't. It'll be fixed in the next version of `buildmer` (it already has been in that package's GitHub page). Within the context of permutes, this should be a cosmetic issue only - it does not impact your results.
